noverify = ["k8s.io/kubernetes","k8s.io/cloud-provider"]

[[constraint]]
  name = "github.infra.cloudera.com/yunikorn/scheduler-interface"
  branch = "master"

[[constraint]]
  name = "github.infra.cloudera.com/yunikorn/yunikorn-core"
  branch = "wwei_predicates"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.14.2"

[[constraint]]
  name = "gotest.tools"
  version = "2.3.0"
