apiVersion: v1
kind: ServiceAccount
metadata:
  name: yunikorn-admin
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: yunikorn-rbac
subjects:
  - kind: ServiceAccount
    name: yunikorn-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io