apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    jobId: "job_2019_01_22_00001"
    queue: "root.sandbox"
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-5s
      image: "alpine:latest"
      command: ["/bin/ash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    jobId: "job_2019_01_22_00001"
    queue: "root.sandbox"
  name: task1
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-5s
      image: "alpine:latest"
      command: ["/bin/ash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sleep
    jobId: "job_2019_01_22_00001"
    queue: "root.sandbox"
  name: task2
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-5s
      image: "alpine:latest"
      command: ["/bin/ash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: "100m"
          memory: "500M"